name: Scheduled TSE Data Scraping

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}-20
        restore-keys: |
          playwright-${{ hashFiles('package-lock.json') }}-
          playwright-

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Build package
      run: npm run build

    - name: Scrape TSE data
      run: npm run scrape -- -o tse-data.json -p

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tse-data.json
        git commit -m "Update TSE data $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push

    - name: Create release if significant changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: data-${{ github.run_number }}
        release_name: TSE Data Update ${{ github.run_number }}
        body: |
          Automated TSE data update from BSI website.
          
          This release contains the latest TSE system details scraped from the official BSI website.
        draft: false
        prerelease: true